name: "Raspberry Pi post disk hook"
stages:
    after-disk:
    - if: '[ -d "/iso/build/recovery.img.root/boot/vc" ]'
      name: "Copy firmware to EFI partition"
      commands:
      - cp -r /iso/build/recovery.img.root/boot/vc/* /iso/build/efi/
